package carPark;


/**
* carPark/CompanyHQPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CP_Start.idl
* Wednesday, 3 April 2019 14:25:22 o'clock BST
*/

public abstract class CompanyHQPOA extends org.omg.PortableServer.Servant
 implements carPark.CompanyHQOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("raise_alarm", new java.lang.Integer (0));
    _methods.put ("register_localServer", new java.lang.Integer (1));
    _methods.put ("remove_localServer", new java.lang.Integer (2));
    _methods.put ("exists_localServer", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // carPark/CompanyHQ/raise_alarm
       {
         carPark.vehEvt evt = carPark.vehEvtHelper.read (in);
         this.raise_alarm (evt);
         out = $rh.createReply();
         break;
       }

       case 1:  // carPark/CompanyHQ/register_localServer
       {
         String serverName = in.read_string ();
         this.register_localServer (serverName);
         out = $rh.createReply();
         break;
       }

       case 2:  // carPark/CompanyHQ/remove_localServer
       {
         String serverName = in.read_string ();
         this.remove_localServer (serverName);
         out = $rh.createReply();
         break;
       }

       case 3:  // carPark/CompanyHQ/exists_localServer
       {
         String serverName = in.read_string ();
         boolean $result = false;
         $result = this.exists_localServer (serverName);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:carPark/CompanyHQ:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CompanyHQ _this() 
  {
    return CompanyHQHelper.narrow(
    super._this_object());
  }

  public CompanyHQ _this(org.omg.CORBA.ORB orb) 
  {
    return CompanyHQHelper.narrow(
    super._this_object(orb));
  }


} // class CompanyHQPOA
