package carPark;


/**
* carPark/EntryGateOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CP_Start.idl
* Wednesday, 3 April 2019 14:25:22 o'clock BST
*/

public interface EntryGateOperations 
{
  String machineName ();
  void turn_on ();
  void turn_off ();
  void reset ();
} // interface EntryGateOperations
