package carPark;

/**
* carPark/ExitGateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CP_Start.idl
* Wednesday, 3 April 2019 14:25:22 o'clock BST
*/

public final class ExitGateHolder implements org.omg.CORBA.portable.Streamable
{
  public carPark.ExitGate value = null;

  public ExitGateHolder ()
  {
  }

  public ExitGateHolder (carPark.ExitGate initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = carPark.ExitGateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    carPark.ExitGateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return carPark.ExitGateHelper.type ();
  }

}
