package carPark;


/**
* carPark/vehEvtLogHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CP_Start.idl
* Wednesday, 3 April 2019 14:25:22 o'clock BST
*/

abstract public class vehEvtLogHelper
{
  private static String  _id = "IDL:carPark/vehEvtLog:1.0";

  public static void insert (org.omg.CORBA.Any a, carPark.vehEvt[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static carPark.vehEvt[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = carPark.vehEvtHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (carPark.vehEvtLogHelper.id (), "vehEvtLog", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static carPark.vehEvt[] read (org.omg.CORBA.portable.InputStream istream)
  {
    carPark.vehEvt value[] = null;
    int _len0 = istream.read_long ();
    value = new carPark.vehEvt[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = carPark.vehEvtHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, carPark.vehEvt[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      carPark.vehEvtHelper.write (ostream, value[_i0]);
  }

}
