package carPark;

/**
* carPark/vehEvtHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CP_Start.idl
* Wednesday, 3 April 2019 14:25:21 o'clock BST
*/

public final class vehEvtHolder implements org.omg.CORBA.portable.Streamable
{
  public carPark.vehEvt value = null;

  public vehEvtHolder ()
  {
  }

  public vehEvtHolder (carPark.vehEvt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = carPark.vehEvtHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    carPark.vehEvtHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return carPark.vehEvtHelper.type ();
  }

}
