package carPark;


/**
* carPark/vehEvtLogHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CP_Start.idl
* Wednesday, 3 April 2019 14:25:22 o'clock BST
*/

public final class vehEvtLogHolder implements org.omg.CORBA.portable.Streamable
{
  public carPark.vehEvt value[] = null;

  public vehEvtLogHolder ()
  {
  }

  public vehEvtLogHolder (carPark.vehEvt[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = carPark.vehEvtLogHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    carPark.vehEvtLogHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return carPark.vehEvtLogHelper.type ();
  }

}
